# vim:ft=kitty

## name: Flexoki (Light)
## author: Kepano
## license: MIT
## upstream: https://raw.githubusercontent.com/kepano/flexoki/main/kitty/flexoki_light.conf



# The basic colors
foreground              #100F0F
background              #FFFCF0
selection_foreground    #100F0F
selection_background    #CECDC3

# Cursor colors
cursor                  #100F0F
cursor_text_color       #FFFCF0

# URL underline color when hovering with mouse
url_color               #205EA6

# Kitty window border colors
active_border_color     #D14D41
inactive_border_color   #CECDC3
bell_border_color       #AD8301

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #100F0F
active_tab_background   #CECDC3
inactive_tab_foreground #6F6E69
inactive_tab_background #E6E4D9
tab_bar_background      #CECDC3

# Colors for marks (marked text in the terminal)
mark1_foreground #FFFCF0
mark1_background #205EA6
mark2_foreground #FFFCF0
mark2_background #5E409D
mark3_foreground #FFFCF0
mark3_background #24837B

# The 16 terminal colors

# black
color0 #100F0F
color8 #6F6E69

# red
color1  #D14D41
color9  #AF3029

# green
color2  #879A39
color10 #66800B

# yellow
color3  #D0A215
color11 #AD8301

# blue
color4  #4385BE
color12 #205EA6

# magenta
color5  #CE5D97
color13 #A02F6F

# cyan
color6  #3AA99F
color14 #24837B

# white
color7  #FFFCF0
color15 #F2F0E5
