# vim:ft=kitty

## name:     Kanagawa Nami
## author:   meni (palette: kanagawa-nami, from kanagawa-fuji.nvim)
## license:  MIT
## upstream: https://github.com/rebelot/kanagawa.nvim (lotus base) + ~/Code/personal/kanagawa-fuji.nvim (nami tuning)



# The basic colors
foreground              #545464
background              #f2ecbc
selection_foreground    #42416a
selection_background    #c9cbd1

# Cursor colors
cursor                  #42416a
cursor_text_color       #f2ecbc

# URL underline color when hovering with mouse
url_color               #73A7BC

# Kitty window border colors
active_border_color     #624c82
inactive_border_color   #585463
bell_border_color       #804900

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #716e61
active_tab_background   #e5ddb0
inactive_tab_foreground #8a8980
inactive_tab_background #d5cea3
tab_bar_background      #dcd5ac

# Colors for marks (marked text in the terminal)
mark1_foreground #f2ecbc
mark1_background #3c5687
mark2_foreground #f2ecbc
mark2_background #624c82
mark3_foreground #f2ecbc
mark3_background #1c5d72

# The 16 terminal colors

# black
color0 #1f1f28
color8 #8a8980

# red
color1 #a71c39
color9 #8e001a

# green
color2  #465d23
color10 #3e5e2f

# yellow
color3  #5e5726
color11 #67532f

# blue
color4  #3c5687
color12 #2e5982

# magenta
color5  #8e3958
color13 #624c82

# cyan
color6  #3b5c57
color14 #385d53

# white
color7  #545464
color15 #42416a
