[window]
decorations = "buttonless"
dynamic_padding = true

[cursor]
style = "Beam"

[font]
size = 22.0

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[general]
live_config_reload = true
import = [
	"~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

# import = [
# 	"~/.config/alacritty/themes/themes/catppuccin_latte.toml"
# ]
