live_config_reload = true
import = [
	"~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]


[window]
decorations = "buttonless"
dynamic_padding = true

[cursor]
style = "Beam"

[font]
size = 22.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"
