###############################################################################################
# THEME: DRACULA
###############################################################################################
[[themes]]
name = "dracula"
[themes.palette]
background = "#1e1f29"
foreground = "#f8f8f2"
black = "#000000"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#bbbbbb"
bright_black = "#555555"
bright_red = "#ff5555"
bright_green = "#50fa7b"
bright_yellow = "#f1fa8c"
bright_blue = "#bd93f9"
bright_magenta = "#ff79c6"
bright_cyan = "#8be9fd"
bright_white = "#ffffff"


###############################################################################################
# THEME: CATPUCCIN
###############################################################################################
[[themes]]
name = "catppuccin"
[themes.palette]
background = "#1e1e2e"  # Base background
foreground = "#d9e0ee"  # Base foreground
black = "#24273a"       # Black
red = "#f38ba8"         # Red
green = "#a6e3a1"       # Green
yellow = "#f9e2af"      # Yellow
blue = "#89dceb"        # Blue
magenta = "#f6c177"     # Magenta
cyan = "#94e2d5"        # Cyan
white = "#cdd6f4"       # White
bright_black = "#575268" # Bright black
bright_red = "#f38ba8"  # Bright red
bright_green = "#a6e3a1" # Bright green
bright_yellow = "#f9e2af" # Bright yellow
bright_blue = "#89dceb"  # Bright blue
bright_magenta = "#f6c177" # Bright magenta
bright_cyan = "#94e2d5"  # Bright cyan
bright_white = "#ffffff"  # Bright white

# Optional component styles
[themes.component_style]
like = { fg = "Magenta", modifiers = ["Bold"] }
selection = { bg = "#575268", fg = "White", modifiers = ["Bold"] }
secondary_row = { bg = "#2a2a3c" }

[[themes]]
name = "catppuccin_frappé"
[themes.palette]
background = "#303446"  # Base
foreground = "#c6d0f5"  # Text
black = "#c6d0f5"       # Text
red = "#e78284"         # Red
green = "#a6d189"       # Green
yellow = "#e5c890"      # Yellow
blue = "#8caaee"        # Blue
magenta = "#ca9ee6"     # Mauve
cyan = "#81c8be"        # Teal
white = "#51576d"       # Surface1
bright_black = "#626880" # Surface2
bright_red = "#ff5555"   # Bright Red (default)
bright_green = "#50fa7b"  # Bright Green (default)
bright_yellow = "#f1fa8c" # Bright Yellow (default)
bright_blue = "#bd93f9"   # Bright Blue (default)
bright_magenta = "#ff79c6" # Bright Magenta (default)
bright_cyan = "#8be9fd"   # Bright Cyan (default)
bright_white = "#ffffff"   # Bright White (default)

[themes.component_style]
like = { fg = "#e78284", modifiers = ["Bold"] }  # Red for likes
selection = { bg = "#85c1dc", fg = "#ffffff", modifiers = ["Bold"] }  # Sapphire background with white text for selection
secondary_row = { bg = "#303446", fg = "#c6d0f5" }  # Base background with text color

[[themes]]
name = "catppuccin_latte"
[themes.palette]
background = "#eff1f5"  # Base
foreground = "#4c4f69"  # Text
black = "#4c4f69"       # Text
red = "#d20f39"         # Red
green = "#40a02b"       # Green
yellow = "#df8e1d"      # Yellow
blue = "#1e66f5"        # Blue
magenta = "#8839ef"     # Mauve
cyan = "#179299"        # Teal
white = "#bcc0cc"       # Surface1
bright_black = "#7c7f93" # Overlay2
bright_red = "#ff5555"   # Bright Red (default)
bright_green = "#50fa7b"  # Bright Green (default)
bright_yellow = "#f1fa8c" # Bright Yellow (default)
bright_blue = "#bd93f9"   # Bright Blue (default)
bright_magenta = "#ff79c6" # Bright Magenta (default)
bright_cyan = "#8be9fd"   # Bright Cyan (default)
bright_white = "#ffffff"   # Bright White (default)

[themes.component_style]
like = { fg = "#d20f39", modifiers = ["Bold"] }  # Red for likes
selection = { bg = "#209fb5", fg = "#ffffff", modifiers = ["Bold"] }  # Sapphire background with white text for selection
secondary_row = { bg = "#dce0e8", fg = "#4c4f69" }  # Crust background with text color

[[themes]]
name = "catppuccin_macchiato"
[themes.palette]
background = "#24273a"  # Base
foreground = "#cad3f5"  # Text
black = "#cad3f5"       # Text
red = "#ed8796"         # Red
green = "#a6da95"       # Green
yellow = "#eed49f"      # Yellow
blue = "#8aadf4"        # Blue
magenta = "#c6a0f6"     # Mauve
cyan = "#8bd5ca"        # Teal
white = "#494d64"       # Surface1
bright_black = "#5b6078" # Surface2
bright_red = "#ff5555"   # Bright Red (default)
bright_green = "#50fa7b"  # Bright Green (default)
bright_yellow = "#f1fa8c" # Bright Yellow (default)
bright_blue = "#bd93f9"   # Bright Blue (default)
bright_magenta = "#ff79c6" # Bright Magenta (default)
bright_cyan = "#8be9fd"   # Bright Cyan (default)
bright_white = "#ffffff"   # Bright White (default)

[themes.component_style]
like = { fg = "#ed8796", modifiers = ["Bold"] }  # Red for likes
selection = { bg = "#7dc4e4", fg = "#ffffff", modifiers = ["Bold"] }  # Sapphire background with white text for selection
secondary_row = { bg = "#24273a", fg = "#cad3f5" }  # Base background with text color

[[themes]]
name = "catppuccin_mocha"
[themes.palette]
background = "#1e1e2e"  # Base
foreground = "#cdd6f4"  # Text
black = "#cdd6f4"       # Text
red = "#f38ba8"         # Red
green = "#a6e3a1"       # Green
yellow = "#f9e2af"      # Yellow
blue = "#89b4fa"        # Blue
magenta = "#cba6f7"     # Mauve
cyan = "#94e2d5"        # Teal
white = "#45475a"       # Surface1
bright_black = "#585b70" # Surface2
bright_red = "#ff5555"   # Bright Red (default)
bright_green = "#50fa7b"  # Bright Green (default)
bright_yellow = "#f1fa8c" # Bright Yellow (default)
bright_blue = "#bd93f9"   # Bright Blue (default)
bright_magenta = "#ff79c6" # Bright Magenta (default)
bright_cyan = "#8be9fd"   # Bright Cyan (default)
bright_white = "#ffffff"   # Bright White (default)

[themes.component_style]
like = { fg = "#f38ba8", modifiers = ["Bold"] }  # Red for likes
selection = { bg = "#74c7ec", fg = "#ffffff", modifiers = ["Bold"] }  # Sapphire background with white text for selection
secondary_row = { bg = "#313244", fg = "#cdd6f4" }  # Base background with text color

###############################################################################################
# THEME: GRUVBOX
###############################################################################################
[[themes]]
name = "gruvbox_dark"
[themes.palette]
background = "#282828"
foreground = "#ebdbb2"
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"

###############################################################################################
# THEME: TOKYONIGHT
###############################################################################################
[[themes]]
name = "tokyonight"
[themes.palette]
background = "#1f2335"
foreground = "#c0caf5"
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#2ac3de"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#eee8d5"
bright_black = "#24283b"
bright_red = "#ff4499"
bright_green = "#73daca"
bright_yellow = "#657b83"
bright_blue = "#839496"
bright_magenta = "#ff007c"
bright_cyan = "#93a1a1"
bright_white = "#fdf6e3"

###############################################################################################
# THEME: KANAGAWA
###############################################################################################
[[themes]]
name = "kanagawa"
[themes.palette]
background = "#1F1F28"  # sumiInk1 (Default background)
foreground = "#DCD7BA"  # fujiWhite (Default foreground)
black = "#16161D"       # sumiInk0 (Dark background)
red = "#E82424"         # samuraiRed (Diagnostic Error)
green = "#98BB6C"       # springGreen (Strings)
yellow = "#DCA561"      # autumnYellow (Git Change)
blue = "#7E9CD8"        # crystalBlue (Functions and Titles)
magenta = "#957FB8"     # oniViolet (Statements and Keywords)
cyan = "#7AA89F"        # waveAqua2 (Types)
white = "#C8C093"       # oldWhite (Dark foreground)

bright_black = "#54546D"   # sumiInk4 (Darker foreground)
bright_red = "#E46876"     # waveRed (Standout specials 1)
bright_green = "#76946A"   # autumnGreen (Git Add)
bright_yellow = "#FF9E3B"  # roninYellow (Diagnostic Warning)
bright_blue = "#9CABCA"    # springViolet2 (Brackets and punctuation)
bright_magenta = "#D27E99" # sakuraPink (Numbers)
bright_cyan = "#A3D4D5"    # lightBlue (Not used but fits for bright cyan)
bright_white = "#DCD7BA"   # fujiWhite (Default foreground)

# Optional component styles
[themes.component_style]
like = { fg = "Red", modifiers = ["Bold"] }
selection = { bg = "#363646", fg = "White", modifiers = ["Bold"] } # sumiInk3 for selection background
secondary_row = { bg = "#223249" } # waveBlue1 for secondary rows
